# Generated by Django 4.2.3 on 2023-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='video',
        ),
        migrations.AddField(
            model_name='applicant',
            name='image_encode_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='video_encode_count',
            field=models.IntegerField(default=0),
        ),
    ]
