# Generated by Django 4.2.3 on 2023-08-02 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_capturedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capturedimage',
            name='image',
            field=models.ImageField(upload_to='db_facerecog/training_video/'),
        ),
    ]
