# Generated by Django 4.2.4 on 2023-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_capturedimage_timestamp_alter_capturedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='image_encode_count',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='video_encode_count',
        ),
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_images/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='applicant_images/'),
        ),
    ]
