# Generated by Django 4.2.4 on 2023-08-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_applicant_image_encode_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='db_facerecog/training/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='db_facerecog/training/'),
        ),
    ]
