# Generated by Django 4.2.4 on 2023-08-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_applicant_image_alter_applicant_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='video',
        ),
    ]
